# Generated by Django 4.2.7 on 2023-11-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
